# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SentencesRecognizer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for SentencesRecognizer
pod 'TesseractOCRiOS', '4.0.0'
  target 'SentencesRecognizerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SentencesRecognizerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
