# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftFB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftFB

pod "FBSDKCoreKit"
pod "FBSDKShareKit"
pod "FBSDKLoginKit"

  target 'SwiftFBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftFBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
